name: Changelog CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review

permissions:
  contents: read
  pull-requests: read

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Changelog CI
        uses: saadmk11/changelog-ci@v1.2.0
